version: '3.7'

services:
  back:
    image: video-markup
    container_name: video-markup
    build:
      context: ./back/
      dockerfile: ./Docker.dockerfile
    command: sh -c "python main.py"
    working_dir: /apps/
    volumes:
      - ./back/:/apps/
      - ./media/:/media/
      - ./media/csv/:/media/csv/
      - ./media/video/:/media/video/
      - ./front/:/front/
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db

  nginx:
    build:
      context: ./configs/
      dockerfile: ./Docker.nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./media:/media
      - ./front:/front
      - ./configs/nginx/:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - back

  certbot:
    image: certbot/certbot:v2.0.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  mongo_data:
    name: mongo_data